### ISSUE TITLE
Client crashes at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [Emafire003/ColoredGlowLib#3]
https://bytebin.lucko.me/8ibD1NREAA

**Comment by Emafire003** [comment]
Which version of minecraft and coloredglowlib are you using? And which of fabric api?
I think the latest version should work

**Comment by Emafire003** [comment]
Oh yeah the api changed so of course it will only work in 1.19. So you will need to use the older version, 1.3.3 which is practly the same.

**Comment by TheButterbrotMan** [comment]
But its taged on cf for 1.18.2

**Comment by Emafire003** [comment]
Well I changed it when I realized my mistake. For 1.18.2 and downwards
please use version 1.3.3 at least for now.

I assumed you were playing using ColoredGlowLib 1.3.4 on a 1.18.2 minecraft version is that correct? If not please send me more details, since I checked and, 1.3.4 should work on 1.19. For more details I mean "Which version of minecraft and coloredglowlib are you using? And which of fabric api?"

**Comment by Emafire003** [comment]
I'm going to assume the issue is fixed since you didn't answer anything back

**Comment by TheButterbrotMan** [comment]
@Emafire003 Ops, didnt saw you replied.
1.18.2, 1.3.4, API:: 0.56.1+1.18.2

**Comment by TheButterbrotMan** [comment]
![image](https://user-images.githubusercontent.com/64548098/175808145-a51d3a74-f8f9-43ac-a9e8-77764e5cc19f.png)
Could you remove the 1.18.2 tag from the 1.3.4 file then please?

**Comment by Emafire003** [comment]
Well I've already removed it weaks ago, probably the curseforge launcher didn't notice but i don't think I can do anything about it.
I'm kinda busy these days but I could look to support both versions in the near future, but not in a single jar. (aka there is gonna be CGL 1.3.5+1.18.2 and CGL 1.3.5+1.19.1 etc.. i think. I don't know I still have to look into it)
